language: php
sudo: false

php:
    - 7.1
    - 7.2

env:
    - SYMFONY_VERSION=3.0.*
    - SYMFONY_VERSION=3.1.*
    - SYMFONY_VERSION=3.2.*
    - SYMFONY_VERSION=3.3.*
    - SYMFONY_VERSION=3.4.*
    - SYMFONY_VERSION=4.0.*
    - SYMFONY_VERSION=4.1.* DEPENDENCIES=dev

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini || true
    - phpenv rehash
    - composer self-update
    - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install:
    - composer install

script:
    - ./vendor/bin/phpunit
