language: php
sudo: false

php:
    - 7.1
    - 7.2

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini || true
    - phpenv rehash
    - composer self-update

install:
    - composer install

script:
    - ./vendor/bin/phpunit
