language: php

sudo: false

php:
    - 5.6
    - 7.0
    - hhvm
    - nightly

before_install:
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] &&  [ "$TRAVIS_PHP_VERSION" < "7.1" ]; then phpenv config-rm xdebug.ini; fi
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv rehash; fi;
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install:
    - composer install

script:
    - phpunit

matrix:
    fast_finish: true
    include:
        - php: 5.6
          env: SYMFONY_VERSION=2.7.*
        - php: 5.6
          env: SYMFONY_VERSION=2.8.*
        - php: 5.6
          env: SYMFONY_VERSION=3.0.*
        - php: 7.0
          env: SYMFONY_VERSION=3.0.*
    allow_failures:
        - php: hhvm
        - php: nightly

notifications:
    email: false
